name: 'OneFourShutter, LLC'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.05744395079091191
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a180b5'
    - '#2e1749'
    - '#babcbe'
    - '#7a529c'
    - '#ffffff'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
